default_platform(:ios)

platform :ios do
  desc "Pass all test for main target"
  lane :pass_tests do
  	test_scheme(scheme: "MagicPills-macOS", configuration: "Debug", name: "mac")
  	test_scheme(scheme: "MagicPills-tvOS", configuration: "Debug", name: "tv")
  	test_scheme(scheme: "MagicPills-iOS", configuration: "Debug", name: "iOS")
  end
end
